name: "test-local"
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: npm ci
      - run: npm test
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: PR comment test
        id: prComment
      - run: echo "Comment URL - ${{ steps.prComment.outputs.commentUrl }}"
        if: steps.prComment.outputs.commentUrl
